-- AR AGEING v8.530.12 (with 5 UDF + 5 BP UDF fields + 5 Value fields)
DROP TABLE "@NCM_AR_AGEING";
CREATE TABLE "@NCM_AR_AGEING"
		(	Username		NVARCHAR(50), 
			Checkpt			NVARCHAR(40),
			CardCode		NVARCHAR(20), 
			ChildCardCode	NVARCHAR(20), 
			DocNum			NVARCHAR(20),
			TransId			NVARCHAR(20), -- PREVIOUSLY INT
			Instl_Id		NVARCHAR(20), -- PREVIOUSLY INT
			InstlmntId		NVARCHAR(10),
			PosDate			DATE,
/*row 10*/	DocDate			DATE,
			DocDueDate		DATE,
			NumAtCard		NVARCHAR(200),
			Ref1			NVARCHAR(200),
			Ref2			NVARCHAR(200),
			Project			NVARCHAR(50),
			Slpcode			SMALLINT,
			DocCur			NVARCHAR(5),
			DocRate			DECIMAL(25,6),
			DocTotal		DECIMAL(25,6),
/*row 20*/	DocTotalFC		DECIMAL(25,6),
			DocType			NVARCHAR(10),
			ClosePaid 		DECIMAL(25,6),
			ClosePaidFC		DECIMAL(25,6),
			OpenAmt			DECIMAL(25,6),
			OpenAmtFC		DECIMAL(25,6),
			IntrnMatch		INTEGER,
			PosAgeDays		INTEGER,
			PosAgeMths		INTEGER,
			DocAgeDays		INTEGER,
/*row 30*/	DocAgeMths		INTEGER,
			DueAgeDays		INTEGER,
			DueAgeMths		INTEGER,
			DocStatus		NVARCHAR(1),
			Cancelled		NVARCHAR(1),
			PaymentCur		NVARCHAR(5),
			PaymentAmt		DECIMAL(25,6),
			PaymentDate		DATE,
			PaymentTerm		NVARCHAR(100),
			CreditLimit		DECIMAL(25,6),
			Series			INTEGER,
			SeriesName		NVARCHAR(8),
			SeriesRemark	NVARCHAR(50),
			U_IRPField1		NVARCHAR(254),
			U_IRPField2		NVARCHAR(254),
			U_IRPField3		NVARCHAR(254),
			U_IRPField4		NVARCHAR(254),
			U_IRPField5		NVARCHAR(254),
			U_IRPBPField1		NVARCHAR(254),
			U_IRPBPField2		NVARCHAR(254),
			U_IRPBPField3		NVARCHAR(254),
			U_IRPBPField4		NVARCHAR(254),
			U_IRPBPField5		NVARCHAR(254),
			Dimension1			NVARCHAR(200),
			Dimension2			NVARCHAR(200)
			);

